database:
  2001:
    username: root
    password: 01234
    url: database1
  2002:
    username: root
    password: 0234
    url: database2
  2003:
    username: root
    password: 0234
    url: database3
#yml配置更加直观，便于阅读每个字段的实际意义
clientIp: 127.0.0.1
